version: '3'

networks:
  nginx_proxy_network:
    external:
      name: nginx_proxy_network

services:
  php:
    image: library/php:8.0-rc-apache
    restart: "always"
    networks:
      - nginx_proxy_network
    environment:
      VIRTUAL_HOST: strategio.digital
      VIRTUAL_HOST_ALIAS: www.strategio.digital,strategio.dev,www.strategio.dev,strategio-digital.cz,www.strategio-digital.cz,strategio.app, www.strategio.app
      LETSENCRYPT_HOST: strategio.digital,www.strategio.digital,strategio.dev,www.strategio.dev,strategio-digital.cz,www.strategio-digital.cz,strategio.app, www.strategio.app
    volumes:
      - ./www:/var/www/html