version: '3'

networks:
  nginx_proxy_network:
    external:
      name: nginx_proxy_network

services:
  app:
    build: .
    restart: "always"
    networks:
      - nginx_proxy_network
    environment:
      VIRTUAL_HOST: strategio.digital
      VIRTUAL_HOST_ALIAS: www.strategio.digital,strategio.dev,www.strategio.dev,strategio-digital.cz,www.strategio-digital.cz,strategio.app, www.strategio.app
      LETSENCRYPT_HOST: strategio.digital,www.strategio.digital,strategio.dev,www.strategio.dev,strategio-digital.cz,www.strategio-digital.cz,strategio.app, www.strategio.app
    volumes:
      - ./.env:/var/www/html/.env
      - ./.htaccess:/var/www/html/.htaccess
      - ./app:/var/www/html/app
      - ./cache:/var/www/html/cache
      - ./log:/var/www/html/log
      - ./vendor:/var/www/html/vendor
      - ./www:/var/www/html/www