version: '3'

networks:
  nginx_proxy_network:
    external:
      name: nginx_proxy_network

services:
  php:
    image: library/php:7.4.7-apache
    restart: "always"
    networks:
      - nginx_proxy_network
    environment:
      VIRTUAL_HOST: strategio.digital
      VIRTUAL_HOST_ALIAS: www.strategio.digital
      LETSENCRYPT_HOST: strategio.digital,www.strategio.digital
    volumes:
      - ./www:/var/www/html